modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Trinsdar/FiniteWater/issues"
license="LGPL-v3"

[[mods]]
modId="nomcchatmoderation"
version="${version}"
displayName="No Minecraft Chat Moderation"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/Trinsdar/NoMcChatModeration"
#logoFile="assets/finitewater/icon.png"
authors="Trinsdar"
description='''Disables Minecraft's new report chat feature cause it's too broken.'''
[[dependencies.nomcchatmoderation]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomcchatmoderation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,]"
    ordering="NONE"
    side="BOTH"